spring:
  application:
    name: zm-scpro-message-receiver

  r2dbc:
    url: r2dbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    properties:
      sslEnabled: false

  grpc:
    server:
      port: ${GRPC_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    zm.gov.moh.zmscpromessagereceiver: INFO
